Updated roles: init_dbserver, and setup_pgd
EnterpriseDB/edb-ansible pull request #584
Opened 2023-08-24 20:18 UTC by dougortiz

Updated roles: 
- init_dbserver
- setup_pgd

All tasks related to: 
- PGD
- PGD CAMO
- PGD GROUP COMMIT SCOPES

2023-08-24 22:00 UTC, vibhorkumar123 requested changes

2023-08-24 22:00 UTC, vibhorkumar123 commented on roles/init_dbserver/tasks/setup_tde.yml
> +    - edb_master_key_location not in pg_data
Why do you have this change? I doubt it's intentional. Please check your branch and rebase accordingly.

2023-08-24 22:00 UTC, vibhorkumar123 commented on roles/init_dbserver/tasks/setup_tde.yml
> +    - edb_master_key_location not in pg_data
This doesn't look correct to me.

2023-08-24 22:00 UTC, vibhorkumar123 commented on roles/setup_pgd/tasks/pg_hba_config.yml
> +
IIRC, we verified that this is not needed for configuration. Any reason for this to be here

2023-08-24 22:00 UTC, vibhorkumar123 commented on roles/setup_pgd/tasks/setup_tde.yml
> +    - edb_master_key_location not in pg_data
This doesn't seem correct to me. Please correct it.

2023-08-24 22:00 UTC, vibhorkumar123 commented on roles/setup_pgd/tasks/verify_tde_vars.yml
> +    msg: "edb_key_wrap_cmd and edb_key_unwrap_cmd are must for initializing a cluster"
Change is not needed

2023-08-24 22:03 UTC, hannahms requested changes
Where are the commit scope files?

2023-08-25 19:33 UTC, hannahms commented on roles/setup_pgd/README.md
> +  1. Only one scope can be configured as default at a time. The variable to configure is: `default_group_cs`
Remove this line

2023-08-25 19:40 UTC, hannahms commented on roles/setup_pgd/tasks/pgd_group_commitscope_configuration.yml
> +                                      join_node_group := false
`join_node_group := true`

2023-08-28 16:51 UTC, hannahms requested changes
Update verify_tde_vars and README

2023-08-28 16:51 UTC, hannahms commented on roles/init_dbserver/tasks/verify_tde_vars.yml
> +    msg: "edb_key_wrap_cmd and edb_key_unwrap_cmd are must for initializing a cluster"
should include something about `with TDE`, these are not required for initializing a cluster, but are for initializing a cluster with TDE.

2023-08-28 16:51 UTC, hannahms commented on roles/setup_pgd/README.md
> +
remove blank lines

2023-08-28 16:51 UTC, hannahms commented on roles/setup_pgd/tasks/verify_tde_vars.yml
> +    msg: "edb_key_wrap_cmd and edb_key_unwrap_cmd are must for initializing a cluster"
Same comment as in init_dbserver

2023-08-28 17:03 UTC, dougortiz commented on roles/setup_pgd/tasks/verify_tde_vars.yml
> +    msg: "edb_key_wrap_cmd and edb_key_unwrap_cmd are must for initializing a cluster"
Updated

2023-08-28 17:36 UTC, hannahms approved these changes
LGTM

2023-08-28 21:46 UTC, vibhorkumar123 reviewed
LGTM!

2023-08-28 21:47 UTC, merged